service: fandanzle-v2

frameworkVersion: ">=1.1.0 <2.0.0"
plugins:
  - serverless-offline
  - serverless-deployment-bucket
  - serverless-prune-plugin
  - serverless-plugin-log-subscription
  - serverless-s3-sync

custom:
  serverless-offline:
    port: 3000 

  localDevStaticFolder: dist

  siteName: devnotnull.com

  ## Webpack 
  webpack:
    webpackConfig: './webpack/serverless/index.js'
    packager: 'yarn' 
    includeModules: true

  ## Retention
  prune:
    automatic: true
    includeLayers: true
    number: 10

  ## 
  deploymentBucket:
    versioning: true
    accelerate: true

  ## S3 bucket for static assets
  s3Sync:
    - bucketName: fandanzle-assets
      bucketPrefix: static/
      localDir: dist/static
    
provider:
  name: aws
  runtime: nodejs12.x
  timeout: 10 
  region: ${opt:region, 'eu-west-2'}
  environment:
    NODE_ENV: ${self:provider.stage}

functions:
  server:
    handler: src/server/handler.handler
    events:
      - http:
          method: GET
          path: /{any+}

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: fandanzle-assets
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: MyPolicy
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: !Join 
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref AssetsBucket
                  - /*
        Bucket: !Ref AssetsBucket
    