service: fandanzle-v2

frameworkVersion: ">=1.1.0 <2.0.0"
plugins:
  - serverless-offline
  - serverless-deployment-bucket
  - serverless-prune-plugin
  - serverless-plugin-log-subscription
  - serverless-s3-sync

custom:
  serverless-offline:
    port: 3000 

  ##
  stackName: ${self:service}-${self:provid

  ##
  localDevStaticFolder: build

  ##
  siteName: devnotnull.com

  ## Retention
  prune:
    automatic: true
    includeLayers: true
    number: 10

  ## 
  deploymentBucket:
    versioning: true
    accelerate: true

  ## S3 bucket for static assets
  s3Sync:
    - bucketName: fandanzle-assets-${self:provider.stage}
      bucketPrefix: static/
      localDir: build/static

## 
package:
  exclude:
    - .cache/**
    - .github/**
    - node_modules/**
    - src/**

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 10 
  region: ${opt:region, 'eu-west-2'}
  environment:
    NODE_ENV: production
    BUILD_TYPE: production

functions:
  server:
    handler: build/serverless.handler
    environment:
      NODE_ENV: production
      BUILD_TYPE: production
    events:
      - http:
          method: GET
          path: /{any+}

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: fandanzle-assets-${self:provider.stage}
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: MyPolicy
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: !Join 
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref AssetsBucket
                  - /*
        Bucket: !Ref AssetsBucket
    