service: devnotnull-ui

frameworkVersion: ">=2.0.0"
variablesResolutionMode: 20210326
plugins:
  - serverless-offline
  - serverless-deployment-bucket
  - serverless-prune-plugin

custom:
  ##
  localDevStaticFolder: build

  ## Retention
  prune:
    automatic: true
    includeLayers: true
    number: 10

  ## 
  deploymentBucket:
    versioning: true
    accelerate: true

  ##
  environment: ${opt:stage, 'development'}

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 10 
  region: ${opt:region, 'eu-west-1'}
  stackName: ${self:service}-${self:custom.environment}
  environment:
    NODE_RUNTIME_ENV: ${self:custom.environment}

functions:
  server:
    handler: build/serverless.handler
    environment:
      NODE_RUNTIME_ENV: ${self:custom.environment}
    events:
      - http:
          path: / # this matches any path, the token 'any' doesn't mean anything special
          method: GET
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: GET