service: fandanzle-v2

frameworkVersion: ">=2.0.0"
plugins:
  - serverless-offline
  - serverless-deployment-bucket
  - serverless-prune-plugin
  - serverless-s3-sync

custom:
  serverless-offline:
    port: 3000 

  ##
  localDevStaticFolder: dist

  ##
  siteName: devnotnull.com

  ## Retention
  prune:
    automatic: true
    includeLayers: true
    number: 10

  ## 
  deploymentBucket:
    versioning: true
    accelerate: true

  ## S3 bucket for static assets
  s3Sync:
    buckets:
    - bucketName: fandanzle-assets-${self:provider.stage}
      endpoint: http://localhost:9000
      bucketPrefix: static/
      localDir: dist

## 
package:
  exclude:
    - .cache/**
    - .github/**
    - node_modules/**
    - src/**

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 10 
  stage: ${opt:stage}
  region: ${opt:region, 'eu-west-2'}
  environment:
    NODE_ENV: production

functions:
  server:
    handler: dist/serverless.handler
    environment:
      NODE_ENV: production
    events:
      - http:
          method: GET
          path: /{any+}

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: fandanzle-assets-${self:provider.stage}
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: MyPolicy
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: !Join 
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref AssetsBucket
                  - /*
        Bucket: !Ref AssetsBucket

    