service: wedding-website-api

frameworkVersion: ">=2.0.0"
plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  serverless-offline:
    port: 3001

  dynamodb:
    tableName: ${self:service}
    stages:
      - offline
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: false
      convertEmptyValues: true
      noStart: false

  defaultRegion: eu-west-1
  region: ${opt:region, self:custom.defaultRegion}
  environment: ${opt:stage, 'sandbox'}

  handlerLocation: "dist/handlers"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2

  environment:
    DYNAMODB_TABLE: ${self:service}

functions:

  create: ${file(./serverless-partials/function-todoCreateSingular.yaml)}
  getAll: ${file(./serverless-partials/function-todoGetAll.yaml)}
  getById: ${file(./serverless-partials/function-todoGetById.yaml)}

resources:
  Resources:
    FunctionTodoIamCreateRole: ${file(./resources/iam-todo-create-role.yaml)}
    FunctionTodoIamReadRole: ${file(./resources/iam-todo-read-role.yaml)}
    DynamoTodoTable: ${file(./resources/dynamodb-todo.yaml)}
