name: 'Assert Branch Naming Convention'
on: pull_request

jobs:
  branch-naming-rules:
    runs-on: self-hosted
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z])+\/([a-z])+'
          allowed_prefixes: 'feat,fix,bug' 
          ignore: main,develop 
          min_length: 5 
          max_length: 100 