name: Deploy Feature

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy-api:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        shell: bash
        working-directory: api

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - run: npm install -g yarn

    - run: yarn install 

    - run: yarn build:prod:pure

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./api
        push: true
        tags: alexbrown201/fandanzle-v2-api:latest
