name: Deploy Feature

on:
  push:
    branches-ignore:
      - main

defaults:
  run:
    shell: bash
    working-directory: api

jobs:
  deploy-api:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: alexbrown201/fandanzle-v2-api:latest
    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'nginx'
        repository: 'https://devnotnull-helm.s3.eu-west-2.amazonaws.com'
        namespace: 'default'
        chart: 'nodejs-template'
        token: '${{ github.token }}'
        values: |
          name: foobar
          image.repository: alexbrown201/fandanzle-v2-api:latest
          port: 3005
          service.type: LoadBalancer
          service.loadBalancerIP: 10.150.10.143
          image.pullPolicy: Always
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG_PROD }}'
