name: Deploy Feature

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy-api:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        shell: bash
        working-directory: api

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - run: npm install -g yarn

    - run: yarn install 

    - run: yarn build

    - name: Set up WireGuard
      uses: egor-tensin/setup-wireguard@v1
      with:
        endpoint: 46.46.46.46:51820
        endpoint_public_key: 9IHlvJqgkVWMq57a0A56XI5IjhnL5gaRhI1Pszk7S24=
        ips: 192.168.143.254/24,fd8c:bc10:5021::192.168.143.254/48
        allowed_ips: 192.168.143.0/24,fd8c:bc10:5021::/48
        private_key: GLEiXhRwFuhw8aPy+HQfSMwwoLU0Sw8jE8MOxZ8GV3w=
        preshared_key: PWAfvVWCjiNV0Uh2DhmXhdRaT326qosSOcaDB3j9dwI=
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./api
        push: true
        tags: alexbrown201/fandanzle-v2-api:latest
