name: On merge to main

on:
  push:
    branches:
      - main

jobs:
  deploy-app:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      KUBECONFIG_FILE: '${{ secrets.KUBECONFIG_PROD }}'

    steps:

    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 2     # default
        verbose: false # default
        arch: amd64    # allowed values: amd64, arm64
        rootdir: ""    # defaults to "PWD"
        workdir: ""    # defaults to "PWD/unfor19-awscli"

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
      
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
        role-duration-seconds: 1200
        role-session-name: MySessionName

    - name: Branch name
      run: echo running on branch ${{ github.ref_name }}

    - run: |
        curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
        sudo apt-get install apt-transport-https --yes
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install helm
        
    - run: 'echo "$VPN_CONFIG" > config.ovpn'
      env:
        VPN_CONFIG: ${{secrets.VPN_CONFIG}}

    - run: 'mkdir ~/.kube && echo "$KUBECONFIG_FILE" > ~/.kube/config'
      env:
        KUBECONFIG_FILE: ${{secrets.KUBECONFIG_PROD}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - run: npm install -g yarn

    - run: yarn install 

    - run: yarn lint 

    - run: yarn test

    - run: yarn build:prod:pure

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: alexbrown201/devnotnull-ui:latest

    - name: Create S3 bucket
      run: aws s3api create-bucket --bucket devnotnull-ui-production --region us-east-1 || true

    - name: Copy S3 bucket assets
      run: aws s3 cp ./build s3://devnotnull-ui-production --recursive
      
    - run: |
        aws s3api put-bucket-cors --bucket devnotnull-ui-production --cors-configuration '{"CORSRules" : [{"AllowedHeaders":["*"],"AllowedMethods":["GET","HEAD", "POST"],"AllowedOrigins":["*"],"ExposeHeaders":[]}]}'

    - run: helm repo add devnotnull https://devnotnull-helm.s3.eu-west-2.amazonaws.com

    - run: helm repo update
 
    - run: helm uninstall devnotnull-ui
      continue-on-error: true

    - run: |
        helm install \
        --namespace default \
        --version 2 \
        --set env.NODE_RUNTIME_ENV=production \
        --set env.CDN_BUCKET=production \
        --set image.repository=alexbrown201/devnotnull-ui:latest \
        --set port=3000 \
        --set service.type=LoadBalancer \
        --set service.loadBalancerIP=10.150.10.134 \
        --set ingress.tls.secretName=devnotnull.com-production \
        --set ingress.annotations."kubernetes\.io/ingress\.class"=traefik \
        --set image.pullPolicy=Always \
        --set replicaCount=10 \
        --set "ingress.hosts[0].host"=devnotnull.com \
        --set "ingress.hosts[0].paths[0].path"=/ \
        devnotnull-ui \
        devnotnull/nodejs